[build-system]
requires = ["hatchling >= 1.27"]
build-backend = "hatchling.build"

[project]
name = "ptv3"
version = "0.0.0"
dependencies = [
  "addict",
  # This assumes CUDA 12.X is installed: https://pypi.org/project/spconv/
  # TODO: Read CUDA version at install time. This is a good approach:
  # https://github.com/NVlabs/curobo/blob/057a96ffb1088531535f9915154f9d0dabd62428/pyproject.toml#L42-L68
  "spconv-cu120",
  "timm",
  "torch"
]
requires-python = ">=3.9"

[tool.ruff]
target-version = "py310"

[tool.ruff.lint]
select = [
  # pyflakes
  "F",
  # pycodestyle
  "E",
  "W",
  # isort
  "I"
]
ignore = [
  # Line too long.
  "E501"
]
